import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ConditionalBars } from "./_components/Bar-Sections/conditional-bars";

import { BarSections } from "./_components/Bar-Sections/main-bars";
import localFont from "next/font/local";

const mongolFont = localFont({
  src: "./font/cmdashitseden.ttf",
  variable: "--font-mongol",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="mn"
      className={`${geistSans.variable} ${geistMono.variable} ${mongolFont.variable} h-full antialiased`}
    >
      <body className="h-full flex flex-row overflow-hidden">
        <ConditionalBars />
        <main className="flex-1 h-full overflow-hidden">{children}</main>
      </body>
    </html>
  );
}
