[
  {
    id: "cmoi2jetp0001ic2h190oebar",
    title: "Эгшиг үсгүүд",
    description: "Монгол эгшиг үсгүүдийг сурах",
    order: 1,
    isCompleted: false,
    levelId: "cmoi2gy340000ic2h5jlo3edx",
    content: [
      {
        id: "cmoi2kr1v0002ic2hivxdi6lt",
        lessonId: "cmoi2jetp0001ic2h190oebar",
        name: "А үсэг",
        text: "А",
        imageUrl: null,
        order: 1,
      },
    ],
    tasks: [
      {
        id: "cmoih3qt80000c22h3xxqkqol",
        lessonId: "cmoi2jetp0001ic2h190oebar",
        type: "MC",
        difficulty: "EASY",
        xpReward: 5,
        question: "Энэ үсэг аль нь вэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 1,
      },
    ],
  },
  {
    id: "cmoii3wk30003c22hivi93ox1",
    title: "Хичээл 1 Үндсэн махбод",
    description: "МОНГОЛ БИЧГИЙН ҮСГИЙН ҮНДСЭН МАХБОД",
    order: 1,
    isCompleted: false,
    levelId: "cmoihchgd0002c22hpnc65sbn",
    content: [
      {
        id: "cmoiiaj3i0004c22h2p6m8nfy",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Титэм",
        text: "Зөвхөн үгийн эхэнд бичнэ. Бичихдээ ялимгүй толгой гаргаж, нар зөв эргүүлэн бичнэ.",
        imageUrl: null,
        order: 1,
      },
      {
        id: "cmoiid0qk0005c22he19t87iu",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Шүд",
        text: "Шүд",
        imageUrl: null,
        order: 2,
      },
      {
        id: "cmoiie0vh0006c22hvz283nma",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Шилбэ",
        text: "Шилбэ",
        imageUrl: null,
        order: 3,
      },
      {
        id: "cmoiifea80007c22htlcj80zs",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Гэдэс",
        text: "Хэт том буюу унжгар, цондгор, бөөрөнхий бичиж болохгүй.",
        imageUrl: null,
        order: 4,
      },
      {
        id: "cmoiiggg10008c22hz3vx82rr",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Сүүл",
        text: "Уужим татна.",
        imageUrl: null,
        order: 5,
      },
      {
        id: "cmoiigzy20009c22hrrmsitol",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Орхиц",
        text: "Орхиц",
        imageUrl: null,
        order: 6,
      },
      {
        id: "cmoiiheo4000ac22hqn1njyk2",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        name: "Нум",
        text: "Нум",
        imageUrl: null,
        order: 7,
      },
    ],
    tasks: [
      {
        id: "cmoiippqi000bc22hc3ftahef",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь титэм бэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 1,
      },
      {
        id: "cmoiiqjtg000cc22h4pam6ppo",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь шүд вэ?",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 2,
      },
      {
        id: "cmoiir7hz000dc22hsc4xgl33",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь шилбэ бэ?",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 3,
      },
      {
        id: "cmoiirovg000ec22h8dn39n98",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь гэдэс вэ?",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 4,
      },
      {
        id: "cmoiis7zy000fc22h1yvswmcc",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь сүүл вэ?",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 5,
      },
      {
        id: "cmoiisn6l000gc22hdq3vpn1z",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь орхиц вэ?",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 6,
      },
      {
        id: "cmoiit3uq000hc22h1gzkt8hj",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь нум бэ?",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 7,
      },
      {
        id: "cmoiixckf000ic22hvhutivse",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Титэм ... бичигддэг",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 11,
      },
      {
        id: "cmoiiy3oz000jc22hp4cfdewu",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Шүд ... бичигддэг",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 22,
      },
      {
        id: "cmoiiz95w000kc22hy8voydzs",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Шилбэ ... бичигддэг",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 33,
      },
      {
        id: "cmoiizv13000lc22hywicrd35",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Гэдэс ... бичигддэг",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 44,
      },
      {
        id: "cmoij0axk000mc22hmxc3se84",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Сүүл ... бичигддэг",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 55,
      },
      {
        id: "cmoij0q0q000nc22hirsieo2x",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Орхиц ... бичигддэг",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 66,
      },
      {
        id: "cmoij158v000oc22hlaowt6g4",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Нум ... бичигддэг",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 77,
      },
      {
        id: "cmoij4t3w000pc22h54dkapxx",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 111,
      },
      {
        id: "cmoij58sf000qc22hfw7dyl4i",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 222,
      },
      {
        id: "cmoij5m3o000rc22h24d2w2hf",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 333,
      },
      {
        id: "cmoij605u000sc22hhasf3pe7",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 444,
      },
      {
        id: "cmoij6fsd000tc22hk3hh82dm",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 555,
      },
      {
        id: "cmoij6yfk000uc22hnpp6ll47",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 666,
      },
      {
        id: "cmoij7gq4000vc22hmu0xly8s",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 777,
      },
      {
        id: "cmoij9p80000wc22hr5f9x8d2",
        lessonId: "cmoii3wk30003c22hivi93ox1",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 777,
      },
    ],
  },
  {
    id: "cmoijbyum000xc22hztpl7ixc",
    title: "Хичээл 2 Үндсэн махбод",
    description: "МОНГОЛ БИЧГИЙН ҮСГИЙН ҮНДСЭН МАХБОД",
    order: 2,
    isCompleted: false,
    levelId: "cmoihchgd0002c22hpnc65sbn",
    content: [
      {
        id: "cmoijffgf000yc22htd4i858i",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Гэзэг",
        text: "Гэзэг",
        imageUrl: null,
        order: 1,
      },
      {
        id: "cmoijfu2a000zc22h9tuukmis",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Эвэр",
        text: "Эвэр",
        imageUrl: null,
        order: 2,
      },
      {
        id: "cmoijg97x0010c22hg79k8588",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Зартиг",
        text: "Зартиг",
        imageUrl: null,
        order: 3,
      },
      {
        id: "cmoijgpq90011c22h3gf47qqj",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Завж",
        text: "Завж",
        imageUrl: null,
        order: 4,
      },
      {
        id: "cmoijh49n0012c22h5nthshug",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Дусал",
        text: "Дусал",
        imageUrl: null,
        order: 5,
      },
      {
        id: "cmoijhjq20013c22hvmv0stkg",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Давхар дусал",
        text: "Давхар дусал",
        imageUrl: null,
        order: 6,
      },
      {
        id: "cmoijhyzr0014c22hstcustja",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        name: "Нуруу",
        text: "Нуруу",
        imageUrl: null,
        order: 7,
      },
    ],
    tasks: [
      {
        id: "cmoijjpyy0015c22hx5nab21y",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь гэзэг вэ?",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 1,
      },
      {
        id: "cmoijk6hz0016c22h802zi410",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь эвэр вэ?",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 2,
      },
      {
        id: "cmoijkjfy0017c22h1u8cl3tf",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь зартиг вэ?",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 3,
      },
      {
        id: "cmoijkxet0018c22hg46myppa",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь завж вэ?",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 4,
      },
      {
        id: "cmoijld8n0019c22h1y37tlut",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь дусал вэ?",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 5,
      },
      {
        id: "cmoijlxti001ac22hnnjrg29x",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь давхар дусал вэ?",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 6,
      },
      {
        id: "cmoijmcpi001bc22h91zl3nyk",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Аль нь нуруу вэ?",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 7,
      },
      {
        id: "cmoijnjcz001cc22hdv0b8lov",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Гэзэг ... бичигддэг.",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 11,
      },
      {
        id: "cmoijnzfk001dc22hav9u6aun",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Эвэр ... бичигддэг.",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 22,
      },
      {
        id: "cmoijoe9o001ec22hrwdpwllx",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Зартиг ... бичигддэг.",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 33,
      },
      {
        id: "cmoijorm2001fc22hknqbxztg",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Завж ... бичигддэг.",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 44,
      },
      {
        id: "cmoijp5kn001gc22ha9za2pbs",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Дусал ... бичигддэг.",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 55,
      },
      {
        id: "cmoijphyc001hc22h2pv3dyib",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Давхар дусал ... бичигддэг.",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 66,
      },
      {
        id: "cmoijpzxi001ic22haml1pyez",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Зөвийг сонго: Нуруу ... бичигддэг.",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 77,
      },
      {
        id: "cmoijrbyi001jc22h46fjq4et",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 111,
      },
      {
        id: "cmoijrufz001kc22hr0i11a22",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 222,
      },
      {
        id: "cmoijs7jq001lc22hnpp700uq",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 333,
      },
      {
        id: "cmoijskiq001mc22hwg0gs7qr",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "Г",
        options: ["А", "Б", "В", "Г"],
        order: 444,
      },
      {
        id: "cmoijt9m0001nc22h3r7hhga3",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "В",
        options: ["А", "Б", "В", "Г"],
        order: 555,
      },
      {
        id: "cmoijto3z001oc22hvr1ef1fx",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "Б",
        options: ["А", "Б", "В", "Г"],
        order: 666,
      },
      {
        id: "cmoiju3yj001pc22h4zqpn9pt",
        lessonId: "cmoijbyum000xc22hztpl7ixc",
        type: "MC",
        difficulty: "EASY",
        xpReward: 3,
        question: "Энэ махбодыг юу гэж нэрлэдэг вэ? ",
        correctAnswer: "А",
        options: ["А", "Б", "В", "Г"],
        order: 777,
      },
    ],
  },
];
